import { useEffect,useState } from "react";
import { api,unwrap } from "../services/api.js";
import { PageHeader,Loading,Empty,money } from "../components/UI.jsx";

const blank={name:"",institution:"",type:"BANK",balance:"0",currency:"INR",maskedNumber:""};
export default function Accounts(){
 const [items,setItems]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[error,setError]=useState("");
 async function load(){try{setItems(unwrap(await api.get("/accounts")))}catch(e){setError(e.response?.data?.message||"Unable to load accounts")}}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();try{if(editing)await api.put(`/accounts/${editing}`,form);else await api.post("/accounts",form);setForm(blank);setEditing(null);load()}catch(e){setError(e.response?.data?.message||"Unable to save account")}}
 async function remove(id){if(confirm("Delete this account?")){await api.delete(`/accounts/${id}`);load()}}
 async function connect(id){await api.post("/bank/connect",{accountId:id});await api.post(`/bank/sync/${id}`);load()}
 return <><PageHeader title="Accounts" subtitle="Keep your financial accounts organized. Bank numbers are always masked." action={<button className="btn btn-primary" data-bs-toggle="modal" data-bs-target="#accountModal" onClick={()=>{setEditing(null);setForm(blank)}}>Add account</button>}/>{error&&<div className="alert alert-danger">{error}</div>}
 <div className="row g-3">{items.length===0?<div className="col-12"><div className="card"><Empty title="No accounts yet" text="Add cash, bank, card, wallet or investment accounts."/></div></div>:items.map(a=><div className="col-12 col-md-6 col-xl-4" key={a.id}><div className="card account-card h-100"><div className="card-body"><div className="d-flex justify-content-between"><div><div className="small text-secondary">{a.institution||"Personal"}</div><h5 className="mb-1">{a.name}</h5></div><span className="badge text-bg-light">{a.type.replace("_"," ")}</span></div><div className="account-balance">{money(a.balance)}</div><div className="d-flex justify-content-between small text-secondary"><span>{a.maskedNumber||"No number"}</span><span>{a.currency}</span></div><div className="small text-secondary mt-3">Updated {new Date(a.updatedAt).toLocaleString()}</div><div className="d-flex gap-2 mt-3"><button className="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#accountModal" onClick={()=>{setEditing(a.id);setForm(a)}}>Edit</button>{a.type==="BANK"&&<button className="btn btn-sm btn-outline-success" onClick={()=>connect(a.id)}>Mock sync</button>}<button className="btn btn-sm btn-outline-danger ms-auto" onClick={()=>remove(a.id)}>Delete</button></div></div></div></div>)}</div>
 <div className="modal fade" id="accountModal" tabIndex="-1"><div className="modal-dialog"><div className="modal-content"><form onSubmit={save}><div className="modal-header"><h5>{editing?"Edit":"Add"} account</h5><button className="btn-close" data-bs-dismiss="modal"/></div><div className="modal-body vstack gap-3">
 <label>Name<input className="form-control" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Institution<input className="form-control" value={form.institution||""} onChange={e=>setForm({...form,institution:e.target.value})}/></label><label>Type<select className="form-select" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="CASH">Cash</option><option value="BANK">Bank account</option><option value="CREDIT_CARD">Credit card</option><option value="WALLET">Wallet</option><option value="INVESTMENT">Investment account</option></select></label><label>Current balance<input className="form-control" type="number" step="0.01" value={form.balance} onChange={e=>setForm({...form,balance:e.target.value})}/></label><label>Currency<input className="form-control" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label>Masked number<input className="form-control" placeholder="XXXX XXXX 1234" value={form.maskedNumber||""} onChange={e=>setForm({...form,maskedNumber:e.target.value})}/></label>
 </div><div className="modal-footer"><button type="button" className="btn btn-light" data-bs-dismiss="modal">Cancel</button><button className="btn btn-primary" data-bs-dismiss="modal">Save</button></div></form></div></div></div></>;
}
