import { useEffect,useState } from "react";
import { api,unwrap } from "../services/api.js";
import { PageHeader,Loading } from "../components/UI.jsx";

const suggestions=["How much did I spend this month?","How much did I spend on food?","Where can I reduce my spending?","Am I on track for my vacation goal?","Compare this month with last month.","What are my biggest expenses?"];

export default function Assistant(){
 const [messages,setMessages]=useState([]),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[conversationId,setConversationId]=useState(null);
 useEffect(()=>{api.get("/ai/conversations").then(r=>{const list=unwrap(r);if(list[0])api.get(`/ai/conversations/${list[0].id}`).then(x=>{const c=unwrap(x);setConversationId(c.id);setMessages(c.messages)})})},[]);
 async function send(text=input){if(!text.trim()||loading)return;const user={role:"user",content:text};setMessages(m=>[...m,user]);setInput("");setLoading(true);try{const r=await api.post("/ai/chat",{message:text,conversationId});const d=unwrap(r);setConversationId(d.conversationId);setMessages(m=>[...m,{role:"assistant",content:d.answer}]);}catch(e){setMessages(m=>[...m,{role:"assistant",content:e.response?.data?.message||"I couldn't process that request."}])}finally{setLoading(false)}}
 return <><PageHeader title="FinanceAI Assistant" subtitle="Ask questions about your recorded finances. Answers use approved backend calculations."/><div className="row justify-content-center"><div className="col-12 col-xl-9"><div className="card assistant-card"><div className="card-body p-0"><div className="assistant-head"><div className="brand-mark">F</div><div><div className="fw-semibold">FinanceAI</div><div className="small text-secondary">Personal finance assistant</div></div></div><div className="chat-body">{messages.length===0&&<div className="text-center py-5"><h4>What would you like to understand?</h4><p className="text-secondary">Try one of the questions below.</p></div>}{messages.map((m,i)=><div key={i} className={`chat-row ${m.role==="user"?"user":""}`}><div className={`chat-bubble ${m.role==="user"?"user-bubble":""}`}>{m.content}</div></div>)}{loading&&<div className="chat-row"><div className="chat-bubble"><span className="typing">Thinking…</span></div></div>}</div><div className="suggestions">{suggestions.map(s=><button key={s} className="btn btn-sm btn-outline-secondary" onClick={()=>send(s)}>{s}</button>)}</div><div className="chat-input"><input className="form-control" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask me about your finances…"/><button className="btn btn-primary" onClick={()=>send()}>Send</button></div></div></div><div className="alert alert-light mt-3 small">FinanceAI is an informational assistant, not a licensed financial advisor. It does not execute transfers or financial transactions.</div></div></div></>;
}
