import { useEffect,useState } from "react";
import { api,unwrap } from "../services/api.js";
import { PageHeader,Empty,money } from "../components/UI.jsx";

export default function Budgets(){
 const [budgets,setBudgets]=useState([]),[categories,setCategories]=useState([]),[form,setForm]=useState({month:new Date().toISOString().slice(0,7),items:[]}),[error,setError]=useState("");
 async function load(){try{const [b,c]=await Promise.all([api.get("/budgets"),api.get("/categories")]);setBudgets(unwrap(b));setCategories(unwrap(c));setForm(f=>({...f,items:unwrap(c).filter(x=>["Food","Transport","Shopping","Entertainment","Bills","Healthcare"].includes(x.name)).map(x=>({categoryId:x.id,name:x.name,amount:0}))}))}catch(e){setError(e.response?.data?.message||"Unable to load budgets")}}
 useEffect(()=>{load()},[]);
 async function create(e){e.preventDefault();try{await api.post("/budgets",{month:form.month,categories:form.items.filter(x=>Number(x.amount)>0).map(x=>({categoryId:x.categoryId,amount:Number(x.amount)}))});load()}catch(e){setError(e.response?.data?.message||"Unable to create budget")}}
 return <><PageHeader title="Budgets" subtitle="Set monthly spending limits and track progress." action={<button className="btn btn-primary" data-bs-toggle="modal" data-bs-target="#budgetModal">New budget</button>}/>{error&&<div className="alert alert-danger">{error}</div>}{budgets.length===0?<div className="card"><Empty title="No budgets yet" text="Create your first monthly budget."/></div>:budgets.map(b=><div className="card mb-3" key={b.id}><div className="card-body"><div className="fw-semibold mb-3">{new Date(b.month).toLocaleString("en-IN",{month:"long",year:"numeric"})}</div>{(b.currentStatus||[]).map(status=><BudgetRow key={status.category} status={status}/>) }{b.currentStatus?.length===0&&b.categories.map(x=><div className="mb-2" key={x.id}>{x.category.name}: {money(x.amount)}</div>)}</div></div>)}
 <div className="modal fade" id="budgetModal" tabIndex="-1"><div className="modal-dialog"><div className="modal-content"><form onSubmit={create}><div className="modal-header"><h5>New monthly budget</h5><button className="btn-close" data-bs-dismiss="modal"/></div><div className="modal-body"><label className="form-label">Month<input className="form-control" type="month" value={form.month} onChange={e=>setForm({...form,month:e.target.value})}/></label>{form.items.map((x,i)=><div className="input-group mt-2" key={x.categoryId}><span className="input-group-text flex-grow-1">{x.name}</span><input className="form-control" type="number" min="0" step="100" value={x.amount} onChange={e=>{const items=[...form.items];items[i]={...items[i],amount:e.target.value};setForm({...form,items})}} placeholder="₹ amount"/></div>)}</div><div className="modal-footer"><button className="btn btn-primary" data-bs-dismiss="modal">Create budget</button></div></form></div></div></div>
 </>;
}
function BudgetRow({status}){const pct=Math.min(100,status.percentage);return <div className="mb-3"><div className="d-flex justify-content-between"><span>{status.category}</span><span>{money(status.spent)} / {money(status.budget)}</span></div><div className="progress my-2" style={{height:8}}><div className={`progress-bar ${status.status==="Exceeded"?"bg-danger":status.status==="Warning"?"bg-warning":"bg-success"}`} style={{width:`${pct}%`}}/></div><div className="small text-secondary">{status.status} · {status.percentage}% used · {money(status.remaining)} remaining</div></div>}
