import { useEffect,useState } from "react";
import { api,unwrap } from "../services/api.js";
import { PageHeader,Empty,money } from "../components/UI.jsx";

const blank={name:"",targetAmount:"",currentAmount:"0",targetDate:"",monthlyContribution:""};
export default function Goals(){
 const [items,setItems]=useState([]),[form,setForm]=useState(blank),[error,setError]=useState("");
 async function load(){try{setItems(unwrap(await api.get("/goals")))}catch(e){setError(e.response?.data?.message||"Unable to load goals")}} useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();try{await api.post("/goals",form);setForm(blank);load()}catch(e){setError(e.response?.data?.message||"Unable to create goal")}}
 async function remove(id){if(confirm("Delete this goal?")){await api.delete(`/goals/${id}`);load()}}
 return <><PageHeader title="Financial goals" subtitle="Turn intentions into measurable milestones." action={<button className="btn btn-primary" data-bs-toggle="modal" data-bs-target="#goalModal">New goal</button>}/>{error&&<div className="alert alert-danger">{error}</div>}{items.length===0?<div className="card"><Empty title="No goals yet" text="Create an emergency fund, vacation, education or other goal."/></div>:<div className="row g-3">{items.map(g=><div className="col-12 col-md-6" key={g.id}><div className="card h-100"><div className="card-body"><div className="d-flex justify-content-between"><h5>{g.name}</h5><button className="btn btn-sm btn-outline-danger" onClick={()=>remove(g.id)}>Delete</button></div><div className="display-6 my-3">{money(g.currentAmount)} <span className="fs-6 text-secondary">/ {money(g.targetAmount)}</span></div><div className="progress mb-2" style={{height:10}}><div className="progress-bar bg-success" style={{width:`${g.percentage}%`}}/></div><div className="d-flex justify-content-between small"><span>{g.percentage}% complete</span><span>{money(g.remaining)} remaining</span></div><hr/><div className="small text-secondary">Monthly contribution: {money(g.monthlyContribution)}<br/>Target date: {new Date(g.targetDate).toLocaleDateString()}<br/>Estimated completion: {g.estimatedCompletionDate?new Date(g.estimatedCompletionDate).toLocaleDateString():"Not available"}</div></div></div></div>)}</div>}
 <div className="modal fade" id="goalModal" tabIndex="-1"><div className="modal-dialog"><div className="modal-content"><form onSubmit={save}><div className="modal-header"><h5>New financial goal</h5><button className="btn-close" data-bs-dismiss="modal"/></div><div className="modal-body vstack gap-3"><label>Name<input className="form-control" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Target amount<input className="form-control" type="number" min="1" value={form.targetAmount} onChange={e=>setForm({...form,targetAmount:e.target.value})} required/></label><label>Current amount<input className="form-control" type="number" min="0" value={form.currentAmount} onChange={e=>setForm({...form,currentAmount:e.target.value})}/></label><label>Target date<input className="form-control" type="date" value={form.targetDate} onChange={e=>setForm({...form,targetDate:e.target.value})} required/></label><label>Monthly contribution<input className="form-control" type="number" min="0" value={form.monthlyContribution} onChange={e=>setForm({...form,monthlyContribution:e.target.value})}/></label></div><div className="modal-footer"><button className="btn btn-primary" data-bs-dismiss="modal">Create goal</button></div></form></div></div></div>
 </>;
}
