import { useEffect, useState } from "react";
import { api, unwrap } from "../services/api.js";
import { PageHeader, Loading, Empty, ErrorAlert, money } from "../components/UI.jsx";

const categories=["Salary","Food","Rent","Transport","Shopping","Bills","Entertainment","Healthcare","Education","Investment","Insurance","Loan","Other"];
const empty={date:new Date().toISOString().slice(0,10),description:"",amount:"",type:"EXPENSE",category:"Other",accountId:"",notes:""};

export default function Transactions(){
  const [items,setItems]=useState([]),[accounts,setAccounts]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[query,setQuery]=useState(""),[type,setType]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
  async function load(){setLoading(true);try{const [t,a]=await Promise.all([api.get(`/transactions?search=${encodeURIComponent(query)}&type=${type}`),api.get("/accounts")]);setItems(unwrap(t).items);setAccounts(unwrap(a));}catch(e){setError(e);}finally{setLoading(false);}}
  useEffect(()=>{load();},[query,type]);
  async function save(e){e.preventDefault();try{if(editing)await api.put(`/transactions/${editing}`,form);else await api.post("/transactions",form);setForm(empty);setEditing(null);load();}catch(e){setError(e);}}
  async function remove(id){if(confirm("Delete this transaction?")){await api.delete(`/transactions/${id}`);load();}}
  return <><PageHeader title="Transactions" subtitle="Track every income and expense." action={<button className="btn btn-primary" onClick={()=>{setEditing(null);setForm(empty)}} data-bs-toggle="modal" data-bs-target="#txModal">Add transaction</button>}/>
    <ErrorAlert error={error}/><div className="card mb-3"><div className="card-body row g-2"><div className="col-md-7"><input className="form-control" placeholder="Search descriptions or notes…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="col-md-3"><select className="form-select" value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option><option value="INCOME">Income</option><option value="EXPENSE">Expense</option></select></div><div className="col-md-2"><button className="btn btn-light w-100" onClick={load}>Refresh</button></div></div></div>
    <div className="card"><div className="table-responsive">{loading?<Loading/>:items.length===0?<Empty title="No transactions" text="Add your first transaction to start analyzing your finances."/>:<table className="table align-middle mb-0"><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Account</th><th>Type</th><th className="text-end">Amount</th><th/></tr></thead><tbody>{items.map(t=><tr key={t.id}><td>{new Date(t.date).toLocaleDateString()}</td><td className="fw-semibold">{t.description}<div className="small text-secondary">{t.notes}</div></td><td><span className="badge text-bg-light">{t.category?.name||"Other"}</span></td><td>{t.account?.name||"—"}</td><td><span className={`badge ${t.type==="INCOME"?"text-bg-success":"text-bg-warning"}`}>{t.type}</span></td><td className="text-end fw-semibold">{money(t.amount)}</td><td><div className="dropdown"><button className="btn btn-sm btn-light" data-bs-toggle="dropdown">•••</button><ul className="dropdown-menu"><li><button className="dropdown-item" onClick={()=>{setEditing(t.id);setForm({...t,date:t.date.slice(0,10),category:t.category?.name||"Other"})}} data-bs-toggle="modal" data-bs-target="#txModal">Edit</button></li><li><button className="dropdown-item text-danger" onClick={()=>remove(t.id)}>Delete</button></li></ul></div></td></tr>)}</tbody></table>}</div></div>
    <div className="modal fade" id="txModal" tabIndex="-1"><div className="modal-dialog modal-lg"><div className="modal-content"><form onSubmit={save}><div className="modal-header"><h5>{editing?"Edit":"Add"} transaction</h5><button className="btn-close" data-bs-dismiss="modal"/></div><div className="modal-body row g-3">
      <Field label="Date"><input className="form-control" type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label="Description"><input className="form-control" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></Field><Field label="Amount"><input className="form-control" type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></Field><Field label="Type"><select className="form-select" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="EXPENSE">Expense</option><option value="INCOME">Income</option></select></Field><Field label="Category"><select className="form-select" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Account"><select className="form-select" value={form.accountId||""} onChange={e=>setForm({...form,accountId:e.target.value||null})}><option value="">No account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Notes" full><textarea className="form-control" value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})}/></Field>
    </div><div className="modal-footer"><button type="button" className="btn btn-light" data-bs-dismiss="modal">Cancel</button><button className="btn btn-primary" data-bs-dismiss="modal">Save transaction</button></div></form></div></div></div>
  </>;
}
function Field({label,children,full}){return <div className={full?"col-12":"col-md-6"}><label className="form-label">{label}</label>{children}</div>}
