import { randomUUID } from "node:crypto";
import { BankProvider } from "./BankProvider.js";

const merchants = [
  ["SWIGGY", "Food"], ["ZOMATO", "Food"], ["UBER", "Transport"],
  ["AMAZON", "Shopping"], ["NETFLIX", "Entertainment"], ["ELECTRICITY BILL", "Bills"],
  ["APOLLO PHARMACY", "Healthcare"], ["ONLINE COURSE", "Education"]
];

export class MockBankProvider extends BankProvider {
  async createConsent({ userId }) {
    return { externalId: `mock-consent-${randomUUID()}`, status: "ACTIVE", provider: "mock" };
  }

  async getConsentStatus() {
    return { status: "ACTIVE", provider: "mock" };
  }

  async requestFinancialInformation() {
    return { provider: "mock", dataAvailable: true };
  }

  async handleCallback(payload) {
    return { accepted: true, provider: "mock", payload: { received: Boolean(payload) } };
  }

  async syncTransactions({ accountId }) {
    const transactions = [];
    for (let i = 0; i < 8; i++) {
      const [merchant, category] = merchants[i % merchants.length];
      transactions.push({
        externalId: `mock-${accountId}-${Date.now()}-${i}`,
        date: new Date(Date.now() - i * 86400000),
        description: merchant,
        amount: Number((350 + i * 125).toFixed(2)),
        type: "EXPENSE",
        category,
        notes: "Generated by MockBankProvider"
      });
    }
    transactions.push({
      externalId: `mock-${accountId}-${Date.now()}-salary`,
      date: new Date(),
      description: "SALARY CREDIT",
      amount: 75000,
      type: "INCOME",
      category: "Salary",
      notes: "Generated by MockBankProvider"
    });
    return transactions;
  }

  async disconnectAccount() {
    return { disconnected: true };
  }
}
